account_id = "e9647a01787b681c8b116ffc2649e12c"
compatibility_date = "2022-09-22"
main = "./src/index.js"
name = "TnyLnk"

kv_namespaces = [
  {binding = "URL_DB", id = "bf98832a3f6e45e18f3c39b6db1d329a", preview_id = "bf98832a3f6e45e18f3c39b6db1d329a"},
]
workers_dev = true

[vars]
URL_CACHE = "apiCache" 
URL_EXPIRATION_TTL = 3600 # seconds

[dev]
ip = "0.0.0.0"
local_protocol = "http"
port = 8787
upstream_protocol = "https"

[env.staging]
kv_namespaces = [
  {binding = "URL_DB", id = "40524f34f8f948059899321bf281ff85"},
]
name = "tnylnk.co staging"
workers_dev = true
[env.staging.vars]
URL_CACHE = "apiCache" 
URL_EXPIRATION_TTL = 3600 # seconds

[env.production]
kv_namespaces = [
  {binding = "URL_DB", id = "40524f34f8f948059899321bf281ff85"},
]
name = "atomic-url"
route = "tnylnk.co/*"
workers_dev = false
[env.production.vars]
URL_CACHE = "apiCache" 
URL_EXPIRATION_TTL = 3600 # seconds
